package bad;

import java.lang.reflect.Array;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class ListStuff {
  public static void updateArray(Object[] oa) {
    oa[0] = LocalDate.now();
  }

  public static <E> E[] getAsArray(List<E> l, Class<E> clazz) {
//    E[] result = (E[])new Object[l.size()]; // hacky, not actually correct
    E[] result = (E[])Array.newInstance(clazz, l.size());
    return result;
  }

  private List<String> ls;
  public static void showAll(List l) {
    l.add(0, LocalDate.now());
    for (Object o : l) {
      System.out.println(o);
    }
  }

  public static void main(String[] args) {
    List<String> l =
        Collections.checkedList(new ArrayList<String>(), String.class);
    l.add("Hello");
    l.add("Bonjour");
//    l.add(LocalDate.now());
//    showAll(l);
//    String s = (String)l.get(0);
    String s = l.get(0); // cast is autogenerated by compiler

    String[] sa = getAsArray(l, String.class);
    for (String st : sa) {
      System.out.println("> " + st);
    }

    System.out.println("Type of array is " + sa.getClass().getName());
    System.out.println("Type of array is " + (new Object[1]).getClass().getName());

    Object [] oa = {new Object()};
    updateArray(oa);
    System.out.println(oa[0]);

    String [] sa2 = {"Hello"};
    updateArray(sa2);
  }
}
