package bad;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class ListStuff {
  public static void showAll(List l) {
    l.add(0, LocalDate.now());
    for (Object o : l) {
      System.out.println(o);
    }
  }

  public static void main(String[] args) {
    List<String> l =
        Collections.checkedList(new ArrayList<String>(), String.class);
    l.add("Hello");
    l.add("Bonjour");
//    l.add(LocalDate.now());
    showAll(l);
//    String s = (String)l.get(0);
    String s = l.get(0); // cast is autogenerated by compiler
  }
}
